
import requests
import os

def send_to_telegram(bot_token, chat_id, video_path):
    """Send video to Telegram using bot API"""
    try:
        print(f"📤 Sending video to Telegram: {video_path}")
        
        # Check if video file exists
        if not os.path.exists(video_path):
            raise Exception(f"Video file not found: {video_path}")
        
        # Telegram API URL
        url = f"https://api.telegram.org/bot{bot_token}/sendVideo"
        
        # Prepare the file and data
        with open(video_path, 'rb') as video_file:
            files = {
                'video': video_file
            }
            data = {
                'chat_id': chat_id,
                'caption': '🎵 Auto-captioned TikTok video\n\nGenerated by TikTok Audio Caption Bot ✨'
            }
            
            # Send the video
            response = requests.post(url, data=data, files=files, timeout=120)
            
            if response.status_code == 200:
                print("✅ Video sent to Telegram successfully!")
                return True
            else:
                error_info = response.json() if response.content else "Unknown error"
                raise Exception(f"Telegram API error: {response.status_code} - {error_info}")
                
    except Exception as e:
        raise Exception(f"Failed to send to Telegram: {e}")
